globocom/opensource

yarn.lock

`yarn.lock` using globo private repo, so it's impossible to set up the project. I search for an env var to set this, but can't find it, so I change the yarn.lock. If there is a better approach to resolve this, let me know.

update yarn.lock with public repository

---

src/components/header.js
src/pages/hacktoberfest.js
src/pages/nosso-time.js

removing validation errors in w3c

W3C Validator

---

src/components/copyright.js
src/components/footer.js

dynamic year in footer

---

src/pages/projetos.js
src/pages/projetos.module.css

Some CSS changes to remove default anchor tag styles so that no
changes are visible between this commit and the previous.

Make project titles links

---

src/components/repo-stats.js

Fix typo (Stars ~> Issues)

---

src/components/sort-repos.js
src/pages/projetos.js

- Ordenar os repos primeiramente pela ordem do nome.
- Ordenar pela ordem de issues (Decrescente).
Relacionado ao https://github.com/globocom/opensource/blob/d15b919e7e7ae7c966e7326673ebeffb9115a97e/TODO.txt#L7

Ordenar lista de projetos

---

src/services/github.js

Not even all members was listed on "Nosso Time" page. I modified it to show all members.

Show all members on "Nosso Time" page

---

src/services/github.js

It removes duplicated graphql query to get paginated members

Refactor getOrgMembers

---

README.md
src/pages/nosso-time.js
src/pages/nosso-time.module.css

- Efeito de zoom no avatar dos membros ao passar o mouse 
- Ao clicar no avatar redireciona pra o github do membro
- Info sobre o github token e o escopo necessário

Efeito hover no avatar dos membros e info sobre token no readme

---

src/services/github.js

For ease of readability and maintenance, i've added year and month to constants.

Add current year  programatically

---

src/components/address-dialog.js
src/components/address-dialog.module.css
src/components/button.js
src/components/header.module.css
src/pages/hacktoberfest.js
src/services/api.js

* Changes `hacktoberfest` progress style
* Creates a dialog to change user data

Update user info

---

Dockerfile

Fix: [CVE-2018-7161](https://www.cvedetails.com/cve/CVE-2018-7161/)

update node version for LTS

---

src/services/github.js

Add fastlane-queue org

---

src/services/api.js

Fixes https://github.com/globocom/opensource/issues/48
Of course this doesn't solve the problem, but right now I think is good to remove it from live page!
I've tried to run the app with docker but it have some problems (I will submit another PR)

Remove sensitive data from @arturfsousa user

---

src/pages/hacktoberfest.js

Closes #42 
Make sure people understand the conditions

Reword hacktoberfest.js

---

package.json
src/components/HacktoberFestCall/HacktoberFestProgress.js
yarn.lock

#47 Fazendo validação de formulário, precisar fazer alguma alteração só falar. :)

add validation form hacktoberfestprogress

---

src/components/Layout/Footer.js

- https://estag.globo.com
- https://talentos.globo.com

Make the copyright page default as other globo's sites

---

Dockerfile

Fixes https://github.com/globocom/opensource/issues/50

Bug Fix/Docker Env

---

README-pt-BR.md
README.md

Translated the README file into Brazilian Portuguese

---

src/services/github.js

warning  'getOrgRepos' is assigned a value but never used

Github: Remove unused methods

---

package.json
src/components/HacktoberFestCall/UserProgress.js
src/pages/coders.js
yarn.lock

Instead of show all the combinations at once like **"pull request(s)"** with this changes all these new states can be appear now...
**hacktoberfest view:**
**coders view:**
from) 
to)

Improve data visualization with treated pluralization
